### ISSUE TITLE
keyboard shortcuts stopped working (FF 74)

### ISSUE THREAD

**Issue by edrex** [piroor/copy-selected-tabs-to-clipboard#5]
First, thank you for this addon! I've been using it for about a year and it has streamlined my workflow a lot. :heart:

About 2 weeks ago, possibly when i updated to FF nightly 74.0a1, the keyboard shortcuts stopped working. I had mapped Ctrl+Shift+L to copy. Troubleshooting steps taken:

 - Map different bindings (Ctrl+Alt+L)
 - Disable all other extensions

Curious if anyone can repro (with latest nightly).

**Comment by piroor** [comment]
This addon simply call its function from the keyboard shortcut, so I think that something is changed on Nightly and it now blocks some features accessing to the clipboard.

Currently I don't know it should be fixed by this addon (I need to update my mind) or by Firefox itself (unexpected regression). Could you narrow down the regression window of Nightly? Mozregression will help such bisection: https://mozilla.github.io/mozregression/

**Comment by edrex** [comment]
I'm still able to use `right click -> "Copy to Clipboard"` so it does seem to be an issue with the keybinding itself. Thanks for the pointers, I will test when I have time and update.

**Comment by piroor** [comment]
I've tested this on Nightly 75.0a1 and a shortcut Alt-Shift-C looks working as expected. Could you try with the latest Nightly?

**Comment by edrex** [comment]
It's working with the latest nightly!
I suspect the issue may have been with native Wayland display support, which I neglected to mention in the issue report (my bad).
